# -*- coding: utf-8 -*-
"""Web scraping tools

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ez8bc0I9xJ75e-s1G_Hy22nR_w8leWlD
"""

# -*- coding: utf-8 -*-
#!/usr/bin/env python

"""
@Project Name  ColabProject_MachineLearning_Note
@File Name:    Web scraping tools
@Software:     Google Colab
@Time:         11 Dec 2021
@Author:       zaicy
@contact:      zaicyxu@gmail.com
@version:      1.0
@Description:  according to Dr.Mu Li
"""

from selenium import webdriver

chrome_options = webdriver.ChromeOptions()
chrome_options.headless = True
Chrome = webdriver.Chrome(
    chrome_options=chrome_options)

page = chrome.get(url)